### ISSUE TITLE
Need database Schema

### ISSUE THREAD

**Issue by SnakeDoc** [MoneyBeets/Narvaro#20]
We need a database Schema written. Should be normalized as best as we can to avoid data duplication and effort while making schema updates. The 449 Form is probably a decent reference to start with.

**Comment by ryan-apfel** [comment]
Is that something we can plan tomorrow as a unit?

**Comment by SnakeDoc** [comment]
yes, let's plan to discuss it.

**Comment by SnakeDoc** [comment]
done with commit ee40577141c6d2849291ce281405195e31da5ee4
