### ISSUE TITLE
Need setters and getters for all dynamic UI controls (textfield, textarea, etc...)

### ISSUE THREAD

**Issue by SnakeDoc** [MoneyBeets/Narvaro#21]
Everything needs a setter and getter in the controller class. TextField, TextArea, DatePicker, etc.

**Comment by SnakeDoc** [comment]
Ryan is working on PR #30  which will ultimately close this.

**Comment by scroft001** [comment]
Ryan could you implement the setter and getter for the new File chooser text field I created? Thanks, I will wait until this is done before I code the text field so we do not have any merge conflicts.

**Comment by ryan-apfel** [comment]
I'll take care of that this evening.

**Comment by SnakeDoc** [comment]
51f533f63d8f14c655eb9e164805f34b90fee90e closes this
