### ISSUE TITLE
Enter Data Tab needs FileChooser implemented

### ISSUE THREAD

**Issue by SnakeDoc** [MoneyBeets/Narvaro#24]
FileChooser is something that is not built into FXML by default.

We'll need to make a text-field and button - the button will open a new FileChooser with a FileFilter to only accept the file type of the 449 Form (I believe xls and xlsx but maybe also csv). After the selection is made, it should update the text-field with the path + filename of the chosen file. This selected file will need to be included when we fetch all entered data and ultimately stored in the db.

**Comment by scroft001** [comment]
I'll work on this
